version: '3.7'

services:

  db:
    image: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: kikekane
      MYSQL_ROOT_PASSWORD: kikekane
    volumes:
      - kikekaneDB:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080

  php:
    restart: unless-stopped
    build:
      context: .
    ports:
      - 9000:9000
    volumes:
      - .:/var/www
    depends_on:
      - db

volumes:
  kikekaneDB:
