version: '3.7'

services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: kikekane
      MYSQL_ROOT_PASSWORD: kikekane
    volumes:
      - kikekaneDB:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  kikekaneDB:
